version: '3.1'

services:
  wordpress:
    image: wordpress:php7.1-apache
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./wp_template:/var/www/html/wp-content/themes/virgilsecurity
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_PASSWORD: example
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
